package fr.unilim.iut.shi_fou_mi.utils.lexicons

data object SpanishLexicon : Lexicon() {
    override val win = "gana"
    override val draw = "empate"
    override val play = "jugar"
    override val pseudo = "seudónimo"
    override val choosePseudo = "Elija su seudónimo (máx. 7 caracteres)"
    override val chooseOpponent = "Elija su oponente"
    override val computer = "computadora"
    override val player = "jugador"
    override val chooseMode = "Elija el modo"
    override val classic = "clásico"
    override val strategic = "estratégico"
    override val chooseAdversaryStrategy = "Elija la estrategia del oponente"
    override val chooseYourStrategy = "Elija su estrategia"
    override val human = "humano"
    override val machine = "máquina"
    override val adaptive = "adaptativo"
    override val back = "volver"
    override val scores = "clasificación"
    override val victories = "victorias"
    override val confirm = "confirmar"
    override val cancel = "cancelar"
    override val yes = "sí"
    override val resetscores = "¿Realmente quieres restablecer los puntajes?"
    override val hostGame = "Crear"
    override val joinGame = "Unirse"
    override val waitingScreen = "Esperando un oponente"
    override val isTopLeadingBoard = "¡{} está en la cima del ranking!"
}